
export const MF_EVENT_0_COOLDOWN_TICK = 'MF_EVENT_0_COOLDOWN_TICK';
export const MF_EVENT_1_MISTING_TICK = 'MF_EVENT_1_MISTING_TICK';
export const MF_EVENT_2_CONDENSATION_TICK = 'MF_EVENT_2_CONDENSATION_TICK';
export const MF_EVENT_3_FANNING_TICK = 'MF_EVENT_3_FANNING_TICK';
