export const CORE_EVENT_START = 'CORE_EVENT_START';
export const CORE_EVENT_CIRCULATION_TICK = 'CORE_EVENT_CIRCULATION_TICK';
export const CORE_EVENT_LIGHT_ON = 'CORE_EVENT_LIGHT_ON';
export const CORE_EVENT_LIGHT_OFF = 'CORE_EVENT_LIGHT_OFF';
export const CORE_EVENT_HUMIDIFIER_TICK = 'CORE_EVENT_HUMIDIFIER_TICK';
export const CORE_EVENT_OVER_HUMIDIFIER_TICK = 'CORE_EVENT_OVER_HUMIDIFIER_TICK';
export const CORE_EVENT_DEHUMIDIFIER_TICK = 'CORE_EVENT_DEHUMIDIFIER_TICK';
export const CORE_CONTROLS_UPDATE = 'CORE_CONTROLS_UPDATE';
export const CORE_SENSOR_READINGS_UPDATE = 'CORE_SENSOR_READINGS_UPDATE';

